### ISSUE TITLE
Отмечать серию просмотренной по окончанию просмотра

### ISSUE THREAD

**Issue by staticdreams** [staticdreams/Soap4TV#19]
<a href="https://github.com/staticdreams"><img src="https://avatars.githubusercontent.com/u/988705?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [staticdreams](https://github.com/staticdreams)**
_Sunday Jan 17, 2016 at 11:30 GMT_
_Originally opened as https://github.com/staticdreams/soap4tv-issues/issues/19_

----

Пока что все это происходит вручную.

**Comment by makoni** [comment]
готово
