### ISSUE TITLE
Другой стиль просмотренных эпизодов вместо тусклых?

### ISSUE THREAD

**Issue by staticdreams** [staticdreams/soap4tv#7]

**Comment by makoni** [comment]
Предлагаю добавить бордер к превьюшкам непросмотренных эпизодов. Белый, например. Будет сразу заметнее - какой эпизод просмотен, какой нет

**Comment by staticdreams** [comment]
Готово. Теперь это выглядит вот так.
![simulator screen shot 11 jan 2016 13 12 46](https://cloud.githubusercontent.com/assets/988705/12233162/1801ea2e-b865-11e5-939d-343304d231be.png)

**Comment by makoni** [comment]
Круто, но затемнение предлагаю всё-таки оставлять у просмотренных :)

**Comment by staticdreams** [comment]
@makoni хаха) думаешь так не очень очевидно какие новые, а какие - нет?)

**Comment by makoni** [comment]
Ну телевизоры то у всех разные. Где-то сразу видно, а где-то надо дождаться пока прогреется :) мне вот кажется что это беспроигрышный вариант :)

**Comment by staticdreams** [comment]
Лады, будет тогда вот так)
![simulator screen shot 11 jan 2016 13 31 55](https://cloud.githubusercontent.com/assets/988705/12233973/73693a84-b86a-11e5-8996-5622d815f9a5.png)

**Comment by makoni** [comment]
Шикарно :)
