### ISSUE TITLE
Если возможно, сохранять позицию просмотра серии

### ISSUE THREAD

**Issue by staticdreams** [staticdreams/Soap4TV#8]
<a href="https://github.com/staticdreams"><img src="https://avatars.githubusercontent.com/u/988705?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [staticdreams](https://github.com/staticdreams)**
_Wednesday Dec 23, 2015 at 12:30 GMT_
_Originally opened as https://github.com/staticdreams/soap4tv-issues/issues/8_

----

Чтоб потом начиналось оттуда откуда закончил

**Comment by makoni** [comment]
Готово
